import React from "react";
import SkillCard from "./SkillCard";
const Skills = () => {
  return (
    <div
      id="Skills"
      className="page-section text-base px-5 m-5"
      data-aos="fade-up"
    >
      <div className="section-title">
        <h2 className="other-header">Skills</h2>
      </div>
      <div className="flex justify-center  " data-aos="fade-up">
        <div id="cards">
          <SkillCard
            name="Docker"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg"
          />
          <SkillCard
            name="Kubernetes"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-plain.svg"
          />
          <SkillCard
            name="GitHub Actions"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/githubactions/githubactions-original.svg"
          />
          <SkillCard
            name="Terraform"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/terraform/terraform-original.svg"
          />
          <SkillCard
            name="Ansible"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ansible/ansible-original.svg"
          />
          <SkillCard
            name="ArgoCD"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/argocd/argocd-original.svg"
          />
          <SkillCard
            name="Helm"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/helm/helm-original.svg"
          />
          <SkillCard
            name="AWS"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/amazonwebservices/amazonwebservices-original-wordmark.svg"
          />
          <SkillCard
            name="Azure"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg"
          />
          <SkillCard
            name="GCP"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg"
          />
          <SkillCard
            name="Nginx"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nginx/nginx-original.svg"
          />
          <SkillCard
            name="Linux"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg"
          />
          <SkillCard
            name="Bash"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bash/bash-original.svg"
          />
          <SkillCard
            name="Git"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg"
          />
          <SkillCard
            name="GitHub"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg"
          />
          <SkillCard
            name="Prometheus"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prometheus/prometheus-original.svg"
          />
          <SkillCard
            name="Grafana"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/grafana/grafana-original.svg"
          />
          <SkillCard
            name="Elasticsearch"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/elasticsearch/elasticsearch-original.svg"
          />
          <SkillCard
            name="Kafka"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachekafka/apachekafka-original.svg"
          />
          <SkillCard
            name="RabbitMQ"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rabbitmq/rabbitmq-original.svg"
          />
          <SkillCard
            name="Redis"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg"
          />
          <SkillCard
            name="Vault"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vault/vault-original.svg"
          />
          <SkillCard
            name="TypeScript"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg"
          />
          <SkillCard
            name="JavaScript"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg"
          />
          <SkillCard
            name="Python"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg"
          />
          <SkillCard
            name="Golang"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original-wordmark.svg"
          />
          <SkillCard
            name="Node.js"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original-wordmark.svg"
          />
          <SkillCard
            name="Flask"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original.svg"
          />
          <SkillCard
            name="React"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg"
          />
          <SkillCard
            name="Next.js"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg"
          />
          <SkillCard
            name="Svelte"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/svelte/svelte-original.svg"
          />
          <SkillCard
            name="PostgreSQL"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg"
          />
          <SkillCard
            name="MongoDB"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg"
          />
          <SkillCard
            name="SqLite"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sqlite/sqlite-plain-wordmark.svg"
          />
          <SkillCard
            name="GraphQL"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg"
          />
          <SkillCard
            name="Firebase"
            img_src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg"
          />
        </div>
      </div>
    </div>
  );
};

export default Skills;
